port: "7083"

control_host: "http://127.0.0.1:7081"

test_routing:
  - port: 8081
    path: "139.180.133.201,45.76.150.82,149.28.157.161:8081"

listeners:
  - proto: "tcp"
    port: 8081
    batch_num: 1
#  - proto: "tcp"
#    port: 8002
#  - proto: "udp"
#    port: 8002
#  - proto: "tcp"
#    port: 8003
#  - proto: "udp"
#    port: 8003
#  - proto: "tcp"
#    port: 8004
#  - proto: "tcp"
#    port: 8005
#  - proto: "udp"
#    port: 443   # HTTP3/QUIC
#  - proto: "tcp"
#    port: 443   # HTTPS

rate_limit:
  qps: 1000
  burst: 2000
  clean_interval: 5

aggregator:
  buffer_size: 5120
  batch_timeout_ms: 20

node:
  provider: "Vultr"
  continent: "Asia"
  country: "Singapore"
  city: "Singapore"
  ip:
    private: "0.0.0.0"
    public: "139.180.133.201"