// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v6.30.0
// source: metrics_processing.protocol

package protocol

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc packet_header.go it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	MetricsService_InitDataPlane_FullMethodName = "/protocol.MetricsService/InitDataPlane"
	MetricsService_SyncMetrics_FullMethodName   = "/protocol.MetricsService/SyncMetrics"
)

// MetricsServiceClient is the probing_client API for MetricsService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
//  -
type MetricsServiceClient interface {
	// ()
	InitDataPlane(ctx context.Context, in *InitRequest, opts ...grpc.CallOption) (*SimpleResponse, error)
	// metrics_processing,
	// ，ProbeResultService
	SyncMetrics(ctx context.Context, in *SyncRequest, opts ...grpc.CallOption) (*SyncResponse, error)
}

type metricsServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewMetricsServiceClient(cc grpc.ClientConnInterface) MetricsServiceClient {
	return &metricsServiceClient{cc}
}

func (c *metricsServiceClient) InitDataPlane(ctx context.Context, in *InitRequest, opts ...grpc.CallOption) (*SimpleResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SimpleResponse)
	err := c.cc.Invoke(ctx, MetricsService_InitDataPlane_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *metricsServiceClient) SyncMetrics(ctx context.Context, in *SyncRequest, opts ...grpc.CallOption) (*SyncResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SyncResponse)
	err := c.cc.Invoke(ctx, MetricsService_SyncMetrics_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// MetricsServiceServer is the controller API for MetricsService service.
// All implementations must embed UnimplementedMetricsServiceServer
// for forwarding compatibility.
//
//  -
type MetricsServiceServer interface {
	// ()
	InitDataPlane(context.Context, *InitRequest) (*SimpleResponse, error)
	// metrics_processing,
	// ，ProbeResultService
	SyncMetrics(context.Context, *SyncRequest) (*SyncResponse, error)
	mustEmbedUnimplementedMetricsServiceServer()
}

// UnimplementedMetricsServiceServer must be embedded to have
// forwarding compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedMetricsServiceServer struct{}

func (UnimplementedMetricsServiceServer) InitDataPlane(context.Context, *InitRequest) (*SimpleResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method InitDataPlane not implemented")
}
func (UnimplementedMetricsServiceServer) SyncMetrics(context.Context, *SyncRequest) (*SyncResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SyncMetrics not implemented")
}
func (UnimplementedMetricsServiceServer) mustEmbedUnimplementedMetricsServiceServer() {}
func (UnimplementedMetricsServiceServer) testEmbeddedByValue()                        {}

// UnsafeMetricsServiceServer may be embedded to opt out of forwarding compatibility for this service.
// Use of this interface is not recommended, as added methods to MetricsServiceServer will
// result in compilation errors.
type UnsafeMetricsServiceServer interface {
	mustEmbedUnimplementedMetricsServiceServer()
}

func RegisterMetricsServiceServer(s grpc.ServiceRegistrar, srv MetricsServiceServer) {
	// If the following call pancis, it indicates UnimplementedMetricsServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&MetricsService_ServiceDesc, srv)
}

func _MetricsService_InitDataPlane_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(InitRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MetricsServiceServer).InitDataPlane(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MetricsService_InitDataPlane_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MetricsServiceServer).InitDataPlane(ctx, req.(*InitRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MetricsService_SyncMetrics_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SyncRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MetricsServiceServer).SyncMetrics(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MetricsService_SyncMetrics_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MetricsServiceServer).SyncMetrics(ctx, req.(*SyncRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// MetricsService_ServiceDesc is the grpc.ServiceDesc for MetricsService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var MetricsService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "protocol.MetricsService",
	HandlerType: (*MetricsServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "InitDataPlane",
			Handler:    _MetricsService_InitDataPlane_Handler,
		},
		{
			MethodName: "SyncMetrics",
			Handler:    _MetricsService_SyncMetrics_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "metrics_processing.protocol",
}

const (
	ConfigService_PushConfig_FullMethodName = "/protocol.ConfigService/PushConfig"
)

// ConfigServiceClient is the probing_client API for ConfigService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
//  -
type ConfigServiceClient interface {
	//
	PushConfig(ctx context.Context, in *PushConfigRequest, opts ...grpc.CallOption) (*SimpleResponse, error)
}

type configServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewConfigServiceClient(cc grpc.ClientConnInterface) ConfigServiceClient {
	return &configServiceClient{cc}
}

func (c *configServiceClient) PushConfig(ctx context.Context, in *PushConfigRequest, opts ...grpc.CallOption) (*SimpleResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SimpleResponse)
	err := c.cc.Invoke(ctx, ConfigService_PushConfig_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ConfigServiceServer is the controller API for ConfigService service.
// All implementations must embed UnimplementedConfigServiceServer
// for forwarding compatibility.
//
//  -
type ConfigServiceServer interface {
	//
	PushConfig(context.Context, *PushConfigRequest) (*SimpleResponse, error)
	mustEmbedUnimplementedConfigServiceServer()
}

// UnimplementedConfigServiceServer must be embedded to have
// forwarding compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedConfigServiceServer struct{}

func (UnimplementedConfigServiceServer) PushConfig(context.Context, *PushConfigRequest) (*SimpleResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method PushConfig not implemented")
}
func (UnimplementedConfigServiceServer) mustEmbedUnimplementedConfigServiceServer() {}
func (UnimplementedConfigServiceServer) testEmbeddedByValue()                       {}

// UnsafeConfigServiceServer may be embedded to opt out of forwarding compatibility for this service.
// Use of this interface is not recommended, as added methods to ConfigServiceServer will
// result in compilation errors.
type UnsafeConfigServiceServer interface {
	mustEmbedUnimplementedConfigServiceServer()
}

func RegisterConfigServiceServer(s grpc.ServiceRegistrar, srv ConfigServiceServer) {
	// If the following call pancis, it indicates UnimplementedConfigServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&ConfigService_ServiceDesc, srv)
}

func _ConfigService_PushConfig_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PushConfigRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ConfigServiceServer).PushConfig(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ConfigService_PushConfig_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ConfigServiceServer).PushConfig(ctx, req.(*PushConfigRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// ConfigService_ServiceDesc is the grpc.ServiceDesc for ConfigService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var ConfigService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "protocol.ConfigService",
	HandlerType: (*ConfigServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "PushConfig",
			Handler:    _ConfigService_PushConfig_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "metrics_processing.protocol",
}

const (
	FaultService_ReportFault_FullMethodName = "/protocol.FaultService/ReportFault"
)

// FaultServiceClient is the probing_client API for FaultService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
//  -
type FaultServiceClient interface {
	//
	ReportFault(ctx context.Context, in *ReportFaultRequest, opts ...grpc.CallOption) (*SimpleResponse, error)
}

type faultServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewFaultServiceClient(cc grpc.ClientConnInterface) FaultServiceClient {
	return &faultServiceClient{cc}
}

func (c *faultServiceClient) ReportFault(ctx context.Context, in *ReportFaultRequest, opts ...grpc.CallOption) (*SimpleResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SimpleResponse)
	err := c.cc.Invoke(ctx, FaultService_ReportFault_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// FaultServiceServer is the controller API for FaultService service.
// All implementations must embed UnimplementedFaultServiceServer
// for forwarding compatibility.
//
//  -
type FaultServiceServer interface {
	//
	ReportFault(context.Context, *ReportFaultRequest) (*SimpleResponse, error)
	mustEmbedUnimplementedFaultServiceServer()
}

// UnimplementedFaultServiceServer must be embedded to have
// forwarding compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedFaultServiceServer struct{}

func (UnimplementedFaultServiceServer) ReportFault(context.Context, *ReportFaultRequest) (*SimpleResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ReportFault not implemented")
}
func (UnimplementedFaultServiceServer) mustEmbedUnimplementedFaultServiceServer() {}
func (UnimplementedFaultServiceServer) testEmbeddedByValue()                      {}

// UnsafeFaultServiceServer may be embedded to opt out of forwarding compatibility for this service.
// Use of this interface is not recommended, as added methods to FaultServiceServer will
// result in compilation errors.
type UnsafeFaultServiceServer interface {
	mustEmbedUnimplementedFaultServiceServer()
}

func RegisterFaultServiceServer(s grpc.ServiceRegistrar, srv FaultServiceServer) {
	// If the following call pancis, it indicates UnimplementedFaultServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&FaultService_ServiceDesc, srv)
}

func _FaultService_ReportFault_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ReportFaultRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FaultServiceServer).ReportFault(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: FaultService_ReportFault_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FaultServiceServer).ReportFault(ctx, req.(*ReportFaultRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// FaultService_ServiceDesc is the grpc.ServiceDesc for FaultService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var FaultService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "protocol.FaultService",
	HandlerType: (*FaultServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "ReportFault",
			Handler:    _FaultService_ReportFault_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "metrics_processing.protocol",
}
