port: "7082"
control_host: "http://127.0.0.1:7081"
access_log: "/root/data-proxy/logs/access.log"

node:
  provider: "Vultr"
  continent: "NorthAmerica"
  country: "US"
  city: "Chicago"
  ip:
    private: "0.0.0.0"
    public: "173.199.92.182"
